### ISSUE TITLE
소개 페이지 동작하지 않음.

### ISSUE THREAD

**Issue by hsol** [ridibooks/rui#5]
https://www.ridicorp.com/rui/
동작하지 않고 있습니다. 확인 부탁 드립니다.

**Comment by hsol** [comment]
github description, README 를 http://ridibooks.github.io/rui/ 로 바꾸는 방향도 좋을 것 같습니다.

**Comment by ryandev421** [comment]
@hsol 
https://rsg.ridicorp.com/
이 url로 바뀐것 같네요..

**Comment by ryandev421** [comment]
@nnyamm https://rsg.ridicorp.com/ 이 url로 바뀐것 맞나요? 맞으면 README 수정부탁드립니다~

**Comment by limeburst** [comment]
이미 닫힌 이슈지만, @hsol 님 의견과 동일하게 https://ridibooks.github.io/rui/ 를 캐노니컬 주소로 사용하는 것에 한 표 던집니다.

GitHub Pages 도메인을 통해 오픈소스가 강조되고, 도메인-호스트 관리 비용도 줄어서요.

**Comment by namenu** [comment]
@nnyamm @earus 
GitLab에서 관리되고 있는 것과 혼란의 여지가 있습니다.
저장소를 GitHub으로 일원화하여 주세요.
당장 GitLab에서 옮기기 어려운 상황이라면 본 repository를 제거하거나 사용되지 않음을 명시해주세요.

**Comment by shrimp1box** [comment]
@namenu 
의견주신날 규진님께 요청드려서 사용되지 않음을 명시 했습니다. (@earus 대응 했다는 걸 잊고 대응하겠다고 말씀을 드렸네요 ㅠㅠ)
RUI가 RSG에 통합되며 해당 저장소는 필요가 없어졌는데요 아직 페이퍼샵에서 의존성을 갖고 있어서 
우선 페이퍼샵에서 의존성 끊은 뒤에 제거하도록 하겠습니다.

이와함께 RSG 공개에 대해 정경님과 함께 논의해서 아래와 같이 방향을 정하였습니다.
```
디자인을 공개하는 것이기 때문에 안내 페이지의 디자인적 완성도에 대한 고민과 UI 텍스트 가이드에 관한 내용 추가 작업 진행.
아사나에 Task 만들어 대응한 후 GitHub 으로 이관하여 공개.
```
